services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Buepro\Easyconf\:
    resource: '../Classes/*'

  Buepro\Easyconf\Configuration\SiteConfiguration:
    arguments:
      $coreCache: '@cache.core'
      $configPath: "%env(TYPO3:configPath)%/sites"
